[package]
name = "ReAET"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = { version = "3.6", features = ["wayland-data-control"] }
bytemuck = { version = "1", features = ["derive"] }
eframe = { version = "0.33", default-features = false, features = ["default_fonts", "wayland", "wgpu", "x11"] }
egui_dnd = { git = "https://github.com/vixen256/hello_egui" }
egui_extras = { version = "0.33", default-features = false }
egui_material_icons = "0.5"
egui_plot = "0.34"
glam = { version = "0.30", features = ["bytemuck", "fast-math", "core-simd"] }
image = { version = "0.25", default-features = false, features = ["bmp", "jpeg", "png", "rayon", "webp"] }
kkdlib = { git = "https://github.com/vixen256/KKdLib-sys" }
parking_lot = { version = "0.12", features = ["nightly", "hardware-lock-elision"] }
pollster = "0.4"
rfd = { version = "0.17", default-features = false, features = ["gtk3", "pollster", "wayland"] }
transform-gizmo-egui = "0.8"
wgpu = { version = "27.0", default-features = false, features = ["gles", "metal", "parking_lot", "std", "vulkan"] }

[features]
bc6h = ["kkdlib/bc6h", "image/avif", "image/nasm"]

[profile.dev.package."*"]
opt-level = 1

[profile.release]
codegen-units = 1
strip = true
panic = "abort"
